# Generated by Django 6.0.4 on 2026-04-09 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesiKnot_App', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='bust',
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='height',
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='hip',
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='waist',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_order_notification',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.AddField(
            model_name='conversation',
            name='custom_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='DesiKnot_App.customorder'),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('customer', 'owner', 'custom_order')},
        ),
    ]
