# Generated by Django 6.0.4 on 2026-04-12 14:14

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesiKnot_App', '0006_alter_message_options_alter_message_sender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_main', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='DesiKnot_Ap_slug_2d9616_idx',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_purchase',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart'], name='DesiKnot_Ap_cart_id_d281cd_idx'),
        ),
        migrations.AddIndex(
            model_name='customorder',
            index=models.Index(fields=['status'], name='DesiKnot_Ap_status_be1176_idx'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
