# Generated by Django 6.0.4 on 2026-04-12 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesiKnot_App', '0007_alter_productimage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='DesiKnot_Ap_cart_id_d281cd_idx',
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='DesiKnot_Ap_custome_5ecb37_idx',
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='DesiKnot_Ap_owner_i_cab3b0_idx',
        ),
        migrations.RemoveIndex(
            model_name='customorder',
            name='DesiKnot_Ap_status_be1176_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='DesiKnot_Ap_convers_bb7c61_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='DesiKnot_Ap_is_read_4a00f0_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='DesiKnot_Ap_name_798adb_idx',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price_at_purchase',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='is_main',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DesiKnot_App.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
