# Generated by Django 6.0.4 on 2026-04-13 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DesiKnot_App', '0008_alter_message_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
    ]
