# Generated by Django 6.0.4 on 2026-04-16 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesiKnot_App', '0012_alter_conversation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conversation',
            name='unique_conversation',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='DesiKnot_Ap_convers_cfd14b_idx',
        ),
        migrations.AddField(
            model_name='message',
            name='custom_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='DesiKnot_App.customorder'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['custom_order', 'created_at'], name='DesiKnot_Ap_custom__cc76f8_idx'),
        ),
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
