# Generated by Django 6.0.4 on 2026-04-16 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesiKnot_App', '0013_remove_conversation_unique_conversation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='custom_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='DesiKnot_App.customorder'),
        ),
    ]
