# Generated by Django 6.0.4 on 2026-04-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesiKnot_App', '0014_alter_message_custom_order'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='DesiKnot_Ap_created_d68f88_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='DesiKnot_Ap_custom__cc76f8_idx',
        ),
        migrations.AddField(
            model_name='customorder',
            name='bust',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customorder',
            name='hip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customorder',
            name='length',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customorder',
            name='shoulder',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customorder',
            name='sleeve_length',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customorder',
            name='waist',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
