# Generated by Django 6.0.4 on 2026-04-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesiKnot_App', '0015_remove_message_desiknot_ap_created_d68f88_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customorder',
            name='sleeve_length',
        ),
        migrations.AlterField(
            model_name='customorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('ready', 'Ready')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
    ]
