# Generated by Django 6.0.4 on 2026-04-20 13:08

import DesiKnot_App.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesiKnot_App', '0016_remove_customorder_sleeve_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customorder',
            name='reference_image',
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/', validators=[DesiKnot_App.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/', validators=[DesiKnot_App.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', validators=[DesiKnot_App.models.validate_image_size]),
        ),
        migrations.CreateModel(
            name='CustomOrderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='custom_orders/', validators=[DesiKnot_App.models.validate_image_size])),
                ('custom_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='DesiKnot_App.customorder')),
            ],
        ),
    ]
