# Generated by Django 6.0.4 on 2026-04-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesiKnot_App', '0017_remove_customorder_reference_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customorder',
            name='is_viewed_by_owner',
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='is_viewed_by_user',
        ),
        migrations.AlterField(
            model_name='customorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('ready', 'Ready')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
