# Generated by Django 6.0.4 on 2026-04-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesiKnot_App', '0018_remove_customorder_is_viewed_by_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='is_archived_by_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customorder',
            name='is_deleted_by_owner',
            field=models.BooleanField(default=False),
        ),
    ]
