# Generated by Django 6.0.4 on 2026-04-21 15:33

import DesiKnot_App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesiKnot_App', '0019_customorder_is_archived_by_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', validators=[DesiKnot_App.models.validate_profile_image]),
        ),
    ]
