# Generated by Django 6.0.4 on 2026-04-22 08:05

import DesiKnot_App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesiKnot_App', '0020_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_images/', validators=[DesiKnot_App.models.validate_image_size]),
        ),
    ]
