# Generated by Django 6.0.4 on 2026-04-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesiKnot_App', '0021_alter_productimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customorder',
            old_name='length',
            new_name='height',
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='shoulder',
        ),
        migrations.AddField(
            model_name='customorder',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='custom_orders/'),
        ),
    ]
