# Generated by Django 6.0.4 on 2026-04-22 14:37

import DesiKnot_App.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesiKnot_App', '0022_rename_length_customorder_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorderimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customorder',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='custom_orders/', validators=[DesiKnot_App.models.validate_image_size]),
        ),
    ]
