# Generated by Django 6.0.4 on 2026-04-23 15:55

import DesiKnot_App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesiKnot_App', '0023_customorderimage_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='additional_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/', validators=[DesiKnot_App.models.validate_image_size]),
        ),
    ]
