# Generated by Django 6.0.4 on 2026-04-24 14:31

import DesiKnot_App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesiKnot_App', '0024_customorder_additional_instructions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', validators=[DesiKnot_App.models.validate_image_size]),
        ),
    ]
