# Generated by Django 6.0.4 on 2026-04-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesiKnot_App', '0026_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
