# Generated by Django 6.0.4 on 2026-05-04 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesiKnot_App', '0027_order_payment_status_order_transaction_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='message',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='chat_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DesiKnot_App.message'),
        ),
        migrations.AddField(
            model_name='notification',
            name='custom_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DesiKnot_App.customorder'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('chat', 'Chat'), ('order', 'Order')], default='chat', max_length=20),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['custom_order', 'created_at'], name='DesiKnot_Ap_custom__cc76f8_idx'),
        ),
    ]
