# Generated by Django 6.0.4 on 2026-05-17 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DesiKnot_App', '0034_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
