# Generated by Django 6.0.4 on 2026-05-20 11:21

import DesiKnot_App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesiKnot_App', '0038_wishlist_seen_alter_wishlist_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ai_model_image',
            field=models.ImageField(blank=True, null=True, upload_to='models/', validators=[DesiKnot_App.models.validate_image_size]),
        ),
    ]
