# Generated by Django 6.0.4 on 2026-05-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesiKnot_App', '0039_product_ai_model_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ai_model_image',
            field=models.ImageField(blank=True, null=True, upload_to='ai_models/'),
        ),
    ]
