# Generated by Django 6.0.4 on 2026-05-20 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DesiKnot_App', '0040_alter_product_ai_model_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ai_model_image',
        ),
    ]
