# Generated by Django 6.0.4 on 2026-06-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesiKnot_App', '0043_order_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='Kathmandu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_zone',
            field=models.CharField(choices=[('inside', 'Inside Kathmandu Valley (Rs. 120)'), ('outside', 'Outside Kathmandu Valley (Rs. 180)')], default='inside', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=120.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved & Processing'), ('shipped', 'Dispatched / In Transit'), ('completed', 'Delivered & Closed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
