# Generated by Django 6.0.4 on 2026-06-17 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DesiKnot_App', '0045_ordermessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderMessage',
        ),
    ]
