# Generated by Django 6.0.4 on 2026-06-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesiKnot_App', '0046_delete_ordermessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved & Processing'), ('shipped', 'Dispatched / In Transit'), ('completed', 'Delivered & Closed'), ('cancelled', 'Cancelled'), ('cancellation_requested', 'Cancellation Requested'), ('refund_processing', 'Refund Processing'), ('refunded', 'Refunded')], default='pending', max_length=40),
        ),
    ]
