# Generated by Django 6.0.4 on 2026-06-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesiKnot_App', '0048_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved & Processing'), ('shipped', 'Dispatched / In Transit'), ('completed', 'Delivered & Closed'), ('refund_processing', 'Refund Processing'), ('refunded', 'Refunded')], default='pending', max_length=40),
        ),
    ]
