# Generated by Django 6.0.4 on 2026-07-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesiKnot_App', '0050_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='agreed_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Set by owner once the custom order is quoted/approved', max_digits=10, null=True),
        ),
    ]
