# Generated by Django 6.0.4 on 2026-07-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesiKnot_App', '0051_customorder_agreed_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_type',
            field=models.CharField(choices=[('flat', 'Flat Lay / Product Only'), ('worn', 'Worn / Styled Look')], default='flat', max_length=10),
        ),
    ]
