# Generated by Django 6.0.4 on 2026-07-13 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DesiKnot_App', '0052_productimage_image_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image_type',
        ),
    ]
