# Generated by Django 6.0.4 on 2026-07-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesiKnot_App', '0053_remove_productimage_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave empty if there is no discount.', max_digits=10, null=True),
        ),
    ]
