# Generated by Django 6.0.4 on 2026-07-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesiKnot_App', '0055_userprofile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Owner's cost per unit — used for profit margin calculation", max_digits=10, null=True),
        ),
    ]
