# Generated by Django 6.0.4 on 2026-07-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesiKnot_App', '0056_product_cost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('seller', 'SELLER'), ('buyer', 'Buyer')], default='buyer', max_length=20),
        ),
    ]
