# Generated by Django 6.0.4 on 2026-07-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesiKnot_App', '0057_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('owner', 'Owner'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
